name: Build SIKULA Executables

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Versione della release (es: v1.0.0)"
        required: true

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            exe_name: "sikula-linux"
            asset_path: "./assets:assets"
            
          - os: windows-latest
            exe_name: "sikula-windows.exe"
            asset_path: "./assets;assets"
            
          - os: macos-latest
            exe_name: "sikula-macos"
            asset_path: "./assets:assets"

    runs-on: ${{ matrix.os }}

    steps:
      - name: Controlla repository
        uses: actions/checkout@v4

      - name: Imposta Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11.9"

      # INSTALLA DIPENDENZE DI SISTEMA
      - name: Installa dipendenze di sistema (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev \
            libfreetype6-dev libportmidi-dev libjpeg-dev libpng-dev \
            python3-dev build-essential

      - name: Installa dipendenze di sistema (macOS)
        if: runner.os == 'macOS'
        run: |
          brew install sdl2 sdl2_image sdl2_mixer sdl2_ttf

      - name: Installa dipendenze Python
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Costruisci eseguibile
        shell: pwsh
        run: |
          pyinstaller --onefile --noconsole `
            --add-data "${{ matrix.asset_path }}" `
            --name "${{ matrix.exe_name }}" `
            src/main.py

      - name: Carica gli artefatti
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.exe_name }}
          path: dist/${{ matrix.exe_name }}
          retention-days: 1

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
        contents: write
    steps:
      - name: Scarica tutti gli artefatti
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true
          path: release-files/

      - name: Rendi eseguibili Linux e macOS
        run: |
          chmod +x release-files/sikula-linux
          chmod +x release-files/sikula-macos

      - name: Crea Release Github
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.version }}
          name: "SIKULA - Release ${{ github.event.inputs.version }}"
          draft: false
          prerelease: false
          files: |
            release-files/sikula-linux
            release-files/sikula-windows.exe
            release-files/sikula-macos